// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCic5qLEdDver4M2oJLQdtFCsjg5JDv02U',
    appId: '1:578472199696:web:de29c1ce9df296419a2c95',
    messagingSenderId: '578472199696',
    projectId: 'condorcodev2',
    authDomain: 'condorcodev2.firebaseapp.com',
    storageBucket: 'condorcodev2.firebasestorage.app',
    measurementId: 'G-BK5MV0MYL2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKFNlcQEvW49jX9zH9lcThR3wYlyAszkc',
    appId: '1:578472199696:android:89c6b0d3ad7219759a2c95',
    messagingSenderId: '578472199696',
    projectId: 'condorcodev2',
    storageBucket: 'condorcodev2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf0SBDtoMJ1Spkd0uRDkMNLJD_qbiiWE4',
    appId: '1:578472199696:ios:b4c5e77cff3a4fdb9a2c95',
    messagingSenderId: '578472199696',
    projectId: 'condorcodev2',
    storageBucket: 'condorcodev2.firebasestorage.app',
    iosBundleId: 'com.condorcode.condorCode',
  );
}
